### ISSUE TITLE
[Bug]Unable to join Server on Minecraft 1.8.9 Launched by SCL 

### ISSUE THREAD

**Issue by kuzuanpa** [Steve-xmh/scl#13]
// 首先是你的启动器版本号
// 通常只要粘贴文件名进来就可以了
启动器版本号：Nightly #4fc21249

// 操作系统版本
// 请务必包含系统名称和系统运行架构
操作系统及其版本：
5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux
KDE Plasma 5.20.5 / KDE Framework 5.78.0 / Qt 5.15.2

// 出现问题的情况
// 发生了什么问题？请简要的说明一下
问题概述：I'll receive java.lang.RuntimeException: Unable to access address of buffer when I click "Join Server"button 

// 崩溃报告
// 如果有所提供的话，请用代码块黏贴到此处
崩溃报告：
*****(Current time)**** io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
Warning: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
        at io.netty.channel.epoll.Native.read(Native Method)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.base/java.lang.Thread.run(Thread.java:955)
```
一些调试信息……
```

// 重现步骤
// 要怎么样才能触发这个问题？请稍微说明一下步骤
重现步骤：
0(?).Install Latest KDE Desktop on Debian bullseye
1.Open SCL
2.Download Minecraft 1.8.9
3.Launch Game
4.MultiPlayer 
5.Add Server 
6.Fill in the blank with any avaliable Minecraft server address
7.Join Server
// 备注
// 如果还有什么需要提一句的话？
备注：Client Launched by HMCL doesn't have this bug
A quick video help to explain the problem.
[simplescreenrecorder-2022-08-01_12.37.58.tar.gz](https://github.com/Steve-xmh/scl/files/9230905/simplescreenrecorder-2022-08-01_12.37.58.tar.gz)

**Comment by Steve-xmh** [comment]
可以的话，请提供 SCL 和 HMCL 的启动参数过来（注意个人登录令牌保密）

我看一下是否是参数问题

**Comment by kuzuanpa** [comment]
Solved in new version)
