### ISSUE TITLE
Optifine 1.17.1 启动报错

### ISSUE THREAD

**Issue by poly000** [Steve-xmh/scl#6]
```
[10:52:48] [Render thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
        at ac.a(SourceFile:65) ~[ac.class:?]
        at dvp.a(SourceFile:2417) ~[dvp.class:?]
        at dvp.a(SourceFile:2412) ~[dvp.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:187) ~[Main.class:?]
        ... 6 more


```

**Comment by poly000** [comment]
已解决，native lib的位置应该是natives
